### ISSUE TITLE
Pepy down (26.11.2021)

### ISSUE THREAD

**Issue by RobWen** [psincraian/pepy#391] opened 2021-11-26 08:05 UTC
Projects stats are down again ? 
Well I cannot imagine that only 8k people downloaded pandas in the last day

Can we help somehow?

**Comment by Ankit404butfound** [comment] 2021-11-28 03:29
I am also seeing this issue, I wanted to check the statistics of pywhatkit but it's exceptionally low.
![Screenshot_2021-11-28-08-58-11-59](https://user-images.githubusercontent.com/54436840/143727729-b1b33418-bd17-4b53-9282-7be5302b2f8c.jpg).

**Comment by hugovk** [comment] 2021-11-28 19:58
This is also affecting other projects (https://github.com/crflynn/pypistats.org/issues/44) and appears to be an upstream problem: https://github.com/pypa/linehaul/issues/61

**Comment by hugovk** [comment] 2021-11-28 21:14
It's this:

> We've identified an issue with the PyPI download statistics documented at https://packaging.python.org/guides/analyzing-pypi-package-downloads/ not updating. A resource quota with our backend providers has been exceeded and we are looking into how to resolve the issue. It may be some time before this can be addressed, but statistics in the meantime should be recoverable.

https://status.python.org/incidents/2jj696st6yn5.

**Comment by psincraian** [comment] 2021-11-30 07:36
Thanks @hugovk, seems that you are right :-)

**Comment by venaturum** [comment] 2021-12-01 12:04
Update from link provided by @hugovk 

> We have begun the process of rearchitecting our data processing pipeline to get below the quotas that are impacting and should begin loading the backlog of data and processing new incoming over the next few days.

> Posted Nov 30, 2021 - 20:35 UTC

**Comment by mpenning** [comment] 2021-12-08 11:45
> over the next few days.

FYI, eight days later I can confirm that stats for these projects still appear to be broken...
- https://pepy.tech/project/ciscoconfparse
- https://pepy.tech/project/napalm

**Comment by edgarriba** [comment] 2021-12-08 12:10
Same for some pytorch related
- https://pepy.tech/project/kornia
- https://pepy.tech/project/pytorch

**Comment by RobWen** [comment] 2021-12-08 12:13
It is still open
https://status.python.org/
No need to post every not working project now...

**Comment by ewdurbin** [comment] 2021-12-10 21:11
Just finished resolving our data pipeline issues, but crucially you should migrate to consuming from the `bigquery-public-data` dataset rather than `the-psf`, and reprocess 2021-11-23 as well as all days since to get the most accurate data. we will likely not be backfilling the `the-psf` dataset.

**Comment by seanlaw** [comment] 2021-12-10 21:45
Thank you for the update @ewdurbin!

**Comment by vaibhavrr1** [comment] 2021-12-11 00:23
To anyone who might find it useful . Here's a link to google data studio showing big query results 

you can export as csv  [https://datastudio.google.com/reporting/1winnmfJpqonjzZKmawTNr_rFksFMkmkz/page/VV9N](url)



![image](https://user-images.githubusercontent.com/16877257/145656487-6bae6be8-401e-4e05-a124-59fe343e74ec.png)

**Comment by vaibhavrr1** [comment] 2021-12-12 16:46
![incidentResolved](https://user-images.githubusercontent.com/16877257/145721325-af7217ea-77ef-445b-9910-a05d0445dd93.PNG)

**Comment by psincraian** [comment] 2021-12-15 09:44
Thanks for the update @ewdurbin, I will update the code and backfill the data

**Closed** 2021-12-22 09:13 UTC

**Comment by psincraian** [comment] 2021-12-22 10:11
All the data is now backfilled :-)
